checks:
    javascript: true

# filter:
#     excluded_paths:
#         - node_modules/*
#         - coverage/*

    tests:
        before:
            - make install

        override:
            - make test
