checks:
    javascript: true

filter:
    excluded_paths:
        - node_modules/*
        - coverage/*

        tests:
            override:
                - command: 'make test'
                    # command: 'istanbul cover --report clover test.js'
                    # command: 'npm run test-scrutinizer'
