checks:
    javascript: true

filter:
    excluded_paths:
        - node_modules/*
        - coverage/*

build:
    tests:
        before:
            - make install

        override:
            - make test
