checks:
    javascript: true

filter:
    excluded_paths:
        - node_modules/*
        - coverage/*

        tests:
            before:
                -
                    command: make install

            override:
                -
                    command: make test
