version: "3"
services:
    express:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            # - DBWEBB_DSN=mongodb://magnus:vb8gGtlQT3@ds129156.mlab.com:29156/maaa16
            - DBWEBB_DSN=mongodb://mongodb:27017/maaa16
        volumes:
            - ./:/app/
            - /app/node_modules/
        ports:
            - 1337:1337
        links:
            - mongodb
        command: "npm start"

    mongodb:
        image: mongo
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod

    # node_latest:
    #     build:
    #         context: .
    #         dockerfile: docker/Dockerfile-node-latest
    #     volumes:
    #         - ./:/app/
    #     ports:
    #         - "3000:3000"
    #
    # node_7:
    #     build:
    #         context: .
    #         dockerfile: docker/Dockerfile-node-7
    #     volumes:
    #         - ./:/app/
    #     ports:
    #         - "3000:3000"
    #
    # node_6:
    #     build:
    #         context: .
    #         dockerfile: docker/Dockerfile-node-6
    #     volumes:
    #         - ./:/app/
    #     ports:
    #         - "3000:3000"
    #
    # node_alpine:
    #     build:
    #         context: .
    #         dockerfile: docker/Dockerfile-node-alpine
    #     volumes:
    #         - ./:/app/
    #     ports:
    #         - "3000:3000"
    #
    # node_7_alpine:
    #     build:
    #         context: .
    #         dockerfile: docker/Dockerfile-node-7-alpine
    #     volumes:
    #         - ./:/app/
    #     ports:
    #         - "3000:3000"
    #
    # node_6_alpine:
    #     build:
    #         context: .
    #         dockerfile: docker/Dockerfile-node-6-alpine
    #     volumes:
    #         - ./:/app/
    #     ports:
    #         - "3000:3000"
