version: "3"
services:
    node900:
        image: node:9.0.0
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www/html/
    node890:
        image: node:8.9.0
        ports:
            - "8089:80"
        volumes:
            - .:/var/www/html
    node6115:
        image: node:6.11.5
        ports:
            - "8061:80"
        volumes:
            - .:/var/www/html
